import 'package:flutter/material.dart';
import 'package:whatsup_flutter_june2020/description.dart';

class Pr58708AppBarShadowColor extends StatefulWidget {
  @override
  _Pr58708AppBarShadowColorState createState() =>
      _Pr58708AppBarShadowColorState();
}

class _Pr58708AppBarShadowColorState extends State<Pr58708AppBarShadowColor> {
  Color shadowColor = Colors.red;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 10,
        shadowColor: shadowColor,
        title: Text('AppBar shadow color'),
      ),
      body: Column(
        children: [
          Description(
            title: 'Description',
            description: [
              'Expose the shadowColor parameter of AppBar and AppBarTheme so that users can specify the color of shadow generated by elevation just like they can when using Material widget.'
            ],
          ),
          Description(
            title: 'Details',
            description: ['Press any button to switch the AppBar shadow color'],
          ),
          ButtonBar(
            alignment: MainAxisAlignment.center,
            children: [
              RaisedButton(
                child: Text('Yellow'),
                onPressed: () => setState(() => shadowColor = Colors.yellow),
              ),
              RaisedButton(
                child: Text('Green'),
                onPressed: () {
                  setState(() => shadowColor = Colors.green);
                },
              ),
              RaisedButton(
                child: Text('Blue'),
                onPressed: () {
                  setState(() => shadowColor = Colors.blue);
                },
              )
            ],
          )
        ],
      ),
    );
  }
}
